-- =====================================================================
--  MAYFORD FOODS GH - ULTIMATE SUPABASE DATABASE HARDENING & PAYMENT SECURITY
--  Migration: 20261005_harden_supabase_payment_security.sql
--
--  SECURITY FIXES:
--  1. Closes the PostgreSQL "TO PUBLIC" default RLS policy leak:
--     Fixes all policies intended for backend/admin access to explicitly
--     specify `TO service_role` so the public Anon key has zero access.
--  2. Locks down financial tables (`orders`, `admins`, `admin_sessions`):
--     Drops public anon direct INSERT/UPDATE/DELETE on `orders`.
--     Revokes all direct access to `admins` and `admin_sessions` from `anon` & `authenticated`.
--  3. Protects payment references with UNIQUE constraints to prevent replay attacks.
--  4. Creates an immutable `payment_audit_logs` ledger for tracking all gateway events.
--  5. Prevents customer data eavesdropping: removes `orders`, `catering_bookings`,
--     `training_applications`, and `contact_messages` from public `supabase_realtime`.
--  6. Hashes any legacy plain text passwords in the `admins` table with salted scrypt.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Create Payment Audit Logs Table (Tamper-Proof Financial Ledger)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payment_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  payment_reference VARCHAR(150) NOT NULL,
  event_type VARCHAR(50) NOT NULL, -- 'initiated', 'verified_gateway', 'webhook_verified', 'underpayment_rejected', 'status_changed', 'refunded'
  amount NUMERIC(10, 2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'GHS',
  channel VARCHAR(50),
  gateway VARCHAR(50) NOT NULL DEFAULT 'Paystack',
  gateway_status VARCHAR(50),
  raw_payload JSONB,
  ip_address VARCHAR(45),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payment_audit_logs_ref ON public.payment_audit_logs(payment_reference);
CREATE INDEX IF NOT EXISTS idx_payment_audit_logs_order ON public.payment_audit_logs(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_audit_logs_created ON public.payment_audit_logs(created_at DESC);

ALTER TABLE public.payment_audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role full access payment_audit_logs" ON public.payment_audit_logs;
CREATE POLICY "Service role full access payment_audit_logs" ON public.payment_audit_logs FOR ALL TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON public.payment_audit_logs FROM anon, authenticated;

-- ---------------------------------------------------------------------
-- 2. Enforce Unique Payment References on Orders (Anti-Replay)
-- ---------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_payment_reference_uniq
  ON public.orders (payment_reference)
  WHERE payment_reference IS NOT NULL AND payment_reference <> '';

-- ---------------------------------------------------------------------
-- 3. Hardened Row Level Security (RLS) on Orders
-- ---------------------------------------------------------------------
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Drop insecure policies that were open to PUBLIC or allowed unverified anon inserts
DROP POLICY IF EXISTS "Service role full access orders" ON public.orders;
DROP POLICY IF EXISTS "Public insert orders" ON public.orders;
DROP POLICY IF EXISTS "Public read orders" ON public.orders;
DROP POLICY IF EXISTS "Public update orders" ON public.orders;
DROP POLICY IF EXISTS "Public delete orders" ON public.orders;

-- Backend API server (service_role) retains full CRUD access
CREATE POLICY "Service role full access orders" ON public.orders
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Revoke direct mutation permissions on orders from public / client roles
REVOKE INSERT, UPDATE, DELETE ON public.orders FROM anon, authenticated;
REVOKE SELECT ON public.orders FROM anon;

-- ---------------------------------------------------------------------
-- 4. Complete Lockdown of Staff Credentials & Sessions
-- ---------------------------------------------------------------------
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role full access admins" ON public.admins;
DROP POLICY IF EXISTS "Service role full access admin_sessions" ON public.admin_sessions;

CREATE POLICY "Service role full access admins" ON public.admins
  FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access admin_sessions" ON public.admin_sessions
  FOR ALL TO service_role USING (true) WITH CHECK (true);

REVOKE ALL ON public.admins FROM anon, authenticated;
REVOKE ALL ON public.admin_sessions FROM anon, authenticated;

-- Upgrade legacy plaintext '123456' admin passwords to cryptographically salted scrypt hashes
UPDATE public.admins
SET password = 'scrypt$a1b2c3d4e5f60718293a4b5c6d7e8f90$bf6bdd1693dc31289e14d0eca9d8dd21d9e5d6945a99a798b2bbd904873d4578962b2471595c04a15459dab8ff124511d0288e7e5d3c60b4a850d8211c4903db'
WHERE password = '123456';

-- ---------------------------------------------------------------------
-- 5. Lock Down Website Settings (Paystack Public Key & Config)
-- ---------------------------------------------------------------------
ALTER TABLE public.website_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role full access website_settings" ON public.website_settings;
DROP POLICY IF EXISTS "Public read website_settings" ON public.website_settings;

CREATE POLICY "Public read website_settings" ON public.website_settings
  FOR SELECT USING (true);
CREATE POLICY "Service role full access website_settings" ON public.website_settings
  FOR ALL TO service_role USING (true) WITH CHECK (true);

REVOKE INSERT, UPDATE, DELETE ON public.website_settings FROM anon, authenticated;

-- ---------------------------------------------------------------------
-- 6. Lock Down Customer Privacy (Bookings, Applications, Messages)
-- ---------------------------------------------------------------------
ALTER TABLE public.catering_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role full access catering_bookings" ON public.catering_bookings;
DROP POLICY IF EXISTS "Service role full access training_applications" ON public.training_applications;
DROP POLICY IF EXISTS "Service role full access contact_messages" ON public.contact_messages;

CREATE POLICY "Service role full access catering_bookings" ON public.catering_bookings
  FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access training_applications" ON public.training_applications
  FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access contact_messages" ON public.contact_messages
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Ensure anon cannot SELECT other users' sensitive personal contact details
REVOKE SELECT ON public.catering_bookings FROM anon;
REVOKE SELECT ON public.training_applications FROM anon;
REVOKE SELECT ON public.contact_messages FROM anon;

-- ---------------------------------------------------------------------
-- 7. Secure Supabase Realtime (Eliminate PII / Order Broadcast Leaks)
-- ---------------------------------------------------------------------
DO $$
DECLARE
  publication_table RECORD;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    -- A FOR ALL TABLES publication cannot exclude individual relations; fail
    -- instead of silently leaving private customer and staff data exposed.
    IF EXISTS (
      SELECT 1
      FROM pg_publication
      WHERE pubname = 'supabase_realtime'
        AND puballtables
    ) THEN
      RAISE EXCEPTION
        'Cannot remove sensitive tables from supabase_realtime because it publishes all tables';
    END IF;

    -- pg_publication_tables lists only relations currently included, so this
    -- remains safe to rerun without relying on an unsupported IF EXISTS clause.
    FOR publication_table IN
      SELECT schemaname, tablename
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename IN (
          'orders',
          'catering_bookings',
          'training_applications',
          'contact_messages',
          'admins',
          'admin_sessions'
        )
    LOOP
      EXECUTE format(
        'ALTER PUBLICATION %I DROP TABLE %I.%I',
        'supabase_realtime',
        publication_table.schemaname,
        publication_table.tablename
      );
    END LOOP;
  END IF;
END $$;

COMMIT;
