-- =====================================================================
--  MAYFORD FOODS GH - COMPLETE SUPABASE (POSTGRESQL) SCHEMA + RLS POLICIES
--  Production Hardened & Audited for Realtime & Payment Security
--
--  SECURITY & ACCESS MODEL:
--    1. Anon Key (Public / Storefront Client):
--       - SELECT on public storefront catalog (menu, categories, banners, media, ratings, settings, visitor counter)
--       - INSERT on orders, catering bookings, training applications, contact feedback, and reviews with strict input validation
--       - Privacy Lockdown: NO arbitrary SELECT on orders, catering bookings, applications, or contact inquiries
--       - Secure Order Tracking: via SECURITY DEFINER function `track_customer_order` (requires matching Order ID + phone digits)
--    2. Service Role Key (Backend API Server):
--       - Full unrestricted administrative CRUD access across all 16 tables
--       - Authoritative server-side pricing recalculation, Paystack HMAC token verification, and Resend email dispatching
--    3. Realtime Publication:
--       - Activated across all dynamic tables (orders, catering, academy applications, messages, visitor counter, menu items, settings)
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
--  1. Admins (staff accounts & branch roles)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.admins CASCADE;
CREATE TABLE public.admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_name VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL CHECK (role IN ('super_admin', 'adabraka_admin', 'dzorwulu_admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.admins (id, admin_name, username, password, role, created_at) VALUES
  (1, 'Mayford Main Admin', 'mainadmin', 'scrypt$a1b2c3d4e5f60718293a4b5c6d7e8f90$bf6bdd1693dc31289e14d0eca9d8dd21d9e5d6945a99a798b2bbd904873d4578962b2471595c04a15459dab8ff124511d0288e7e5d3c60b4a850d8211c4903db', 'super_admin', '2026-06-19 16:40:05+00'),
  (2, 'Adabraka Admin', 'adabraka', 'scrypt$a1b2c3d4e5f60718293a4b5c6d7e8f90$bf6bdd1693dc31289e14d0eca9d8dd21d9e5d6945a99a798b2bbd904873d4578962b2471595c04a15459dab8ff124511d0288e7e5d3c60b4a850d8211c4903db', 'adabraka_admin', '2026-06-19 16:40:05+00'),
  (3, 'Dzorwulu Admin', 'dzorwulu', 'scrypt$a1b2c3d4e5f60718293a4b5c6d7e8f90$bf6bdd1693dc31289e14d0eca9d8dd21d9e5d6945a99a798b2bbd904873d4578962b2471595c04a15459dab8ff124511d0288e7e5d3c60b4a850d8211c4903db', 'dzorwulu_admin', '2026-06-19 16:40:05+00');
SELECT setval(pg_get_serial_sequence('public.admins', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.admins));

-- ---------------------------------------------------------------------
--  2. Admin Sessions (persistent express-session store)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.admin_sessions CASCADE;
CREATE TABLE public.admin_sessions (
  sid VARCHAR(128) PRIMARY KEY,
  sess TEXT NOT NULL,
  expire BIGINT NOT NULL
);
CREATE INDEX idx_admin_sessions_expire ON public.admin_sessions (expire);

-- ---------------------------------------------------------------------
--  3. Banners (top announcement bar messages)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.banners CASCADE;
CREATE TABLE public.banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  banner_text VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.banners (id, banner_text, created_at) VALUES
  (1, 'Available on Bolt Food & Direct Online Ordering', '2026-06-19 16:56:31+00'),
  (2, 'Outside Catering Available for Weddings & Corporate Events', '2026-06-19 16:56:31+00'),
  (3, 'Open Monday - Sunday 9:00 AM - 9:30 PM', '2026-06-19 16:56:31+00'),
  (4, 'Community Outreach Programs & Food Donations', '2026-06-19 16:56:31+00'),
  (5, 'Culinary & Hospitality Training Academy Admissions Open', '2026-06-19 16:56:31+00');
SELECT setval(pg_get_serial_sequence('public.banners', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.banners));

-- ---------------------------------------------------------------------
--  4. Catering Bookings (event inquiries & bookings)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.catering_bookings CASCADE;
CREATE TABLE public.catering_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  event_date DATE NOT NULL,
  guest_count INTEGER NOT NULL CHECK (guest_count > 0),
  location TEXT NOT NULL,
  menu_preferences TEXT,
  budget NUMERIC(10, 2),
  outlet VARCHAR(100) NOT NULL CHECK (outlet IN ('Adabraka', 'Dzorwulu')),
  status VARCHAR(50) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Confirmed', 'Cancelled')),
  notification_status VARCHAR(20) NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_catering_bookings_outlet_status ON public.catering_bookings (outlet, status, event_date);

INSERT INTO public.catering_bookings (
  id, customer_name, phone, event_type, event_date, guest_count,
  location, menu_preferences, budget, outlet, status, notification_status, created_at
) VALUES
  (1, 'Dr. Emmanuel Quaye', '0244987654', 'Corporate Luncheon', '2026-07-15', 75, 'Airport Residential, Accra', 'Jollof buffet with grilled chicken and fresh salads', 4500.00, 'Dzorwulu', 'Confirmed', 'seen', '2026-06-20 10:00:00+00'),
  (2, 'Sarah Adjei', '0555123456', 'Wedding Reception', '2026-08-01', 150, 'Asylum Down, Accra', 'Full Ghanaian & continental banquet buffet', 9000.00, 'Adabraka', 'Pending', 'new', '2026-06-21 14:30:00+00');
SELECT setval(pg_get_serial_sequence('public.catering_bookings', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.catering_bookings));

-- ---------------------------------------------------------------------
--  5. Community Media (outreach photos and videos)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.community_media CASCADE;
CREATE TABLE public.community_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  media_type VARCHAR(20) NOT NULL CHECK (media_type IN ('image', 'video')),
  file_name VARCHAR(255) NOT NULL,
  poster_url TEXT,
  event_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.community_media (id, title, description, media_type, file_name, event_date, created_at) VALUES
  (1, 'Adabraka Youth Food Distribution', 'Supporting local families with warm meals and nutritious food packs during the holidays.', 'image', 'hero.png', '2026-05-12', '2026-06-19 17:00:00+00'),
  (2, 'Dzorwulu School Outreach', 'Providing lunch packs to over 200 school children as part of our weekly community mission.', 'image', 'riceball.jpg', '2026-05-26', '2026-06-19 17:05:00+00');
SELECT setval(pg_get_serial_sequence('public.community_media', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.community_media));

-- ---------------------------------------------------------------------
--  6. Contact Messages (feedback & inquiries)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.contact_messages CASCADE;
CREATE TABLE public.contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  subject VARCHAR(255) NOT NULL DEFAULT 'General Inquiry',
  message TEXT NOT NULL,
  notification_status VARCHAR(20) NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_contact_messages_created ON public.contact_messages (created_at DESC);

INSERT INTO public.contact_messages (id, full_name, email, subject, message, notification_status, created_at) VALUES
  (1, 'Kofi Boateng', 'kofi.b@example.com', 'Corporate Event Inquiry', 'Hello, do you cater for weekend outdoor corporate retreats in East Legon?', 'seen', '2026-06-20 09:15:00+00'),
  (2, 'Naa Densua', '0244001122', 'Food Feedback', 'The smoky party jollof ordered to Dzorwulu yesterday was delicious!', 'new', '2026-06-22 11:45:00+00');
SELECT setval(pg_get_serial_sequence('public.contact_messages', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.contact_messages));

-- ---------------------------------------------------------------------
--  7. Menu Categories (food taxonomy)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.menu_categories CASCADE;
CREATE TABLE public.menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.menu_categories (id, category_name, created_at) VALUES
  (1, 'Rice Dishes', '2026-06-19 16:45:00+00'),
  (2, 'Local Dishes', '2026-06-19 16:45:00+00'),
  (3, 'Soups & Stews', '2026-06-19 16:45:00+00'),
  (4, 'Drinks & Beverages', '2026-06-19 16:45:00+00'),
  (5, 'Sides & Extras', '2026-06-19 16:45:00+00');
SELECT setval(pg_get_serial_sequence('public.menu_categories', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.menu_categories));

-- ---------------------------------------------------------------------
--  8. Menu Items (food catalog & discounts)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.menu_items CASCADE;
CREATE TABLE public.menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  food_name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  image VARCHAR(255) NOT NULL DEFAULT 'Jollof.png',
  status VARCHAR(20) NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'unavailable')),
  discount_percent INTEGER NOT NULL DEFAULT 0 CHECK (discount_percent BETWEEN 0 AND 90),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_menu_items_category_status ON public.menu_items (category, status);

INSERT INTO public.menu_items (id, food_name, category, description, price, image, status, discount_percent, created_at) VALUES
  (1, 'Jollof', 'Rice Dishes', 'Smoky Ghanaian Jollof served with grilled chicken, salad and spicy shito sauce', 80.00, 'Jollof.png', 'available', 0, '2026-06-19 16:47:00+00'),
  (2, 'Banku', 'Local Dishes', 'Freshly prepared corn and cassava dough served with rich okro soup and tilapia', 45.00, 'bankuokro.jpeg', 'available', 0, '2026-06-19 16:48:00+00'),
  (3, 'Fried Rice Special', 'Rice Dishes', 'Seasoned wok-fried rice with fresh garden vegetables and grilled chicken', 85.00, 'hero.png', 'available', 0, '2026-06-19 16:49:00+00');
SELECT setval(pg_get_serial_sequence('public.menu_items', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.menu_items));

-- ---------------------------------------------------------------------
--  9. Orders (online and in-store food orders & settlements)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.orders CASCADE;
CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR(255) NOT NULL,
  customer_email VARCHAR(255),
  phone VARCHAR(50) NOT NULL,
  food_item VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  outlet VARCHAR(100) NOT NULL CHECK (outlet IN ('Adabraka', 'Dzorwulu')),
  order_type VARCHAR(100) NOT NULL CHECK (order_type IN ('Delivery', 'Pickup')),
  order_source VARCHAR(30) NOT NULL DEFAULT 'Online' CHECK (order_source IN ('Online', 'In-Store')),
  delivery_zone VARCHAR(120),
  delivery_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  address TEXT,
  order_details TEXT,
  total NUMERIC(10, 2) NOT NULL CHECK (total >= 0),
  payment_method VARCHAR(50) NOT NULL DEFAULT 'Paystack',
  payment_status VARCHAR(50) NOT NULL DEFAULT 'Pending' CHECK (payment_status IN ('Paid', 'Pending', 'Refunded')),
  payment_reference VARCHAR(150),
  status VARCHAR(50) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Preparing', 'Ready', 'Completed')),
  notification_status VARCHAR(20) NOT NULL DEFAULT 'new',
  order_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_orders_outlet_status ON public.orders (outlet, status, payment_status, order_date DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_payment_reference_uniq ON public.orders (payment_reference) WHERE payment_reference IS NOT NULL;

INSERT INTO public.orders (
  id, customer_name, customer_email, phone, food_item, quantity, outlet, order_type,
  delivery_zone, delivery_fee, address, order_details, total,
  payment_method, payment_status, payment_reference, status, notification_status, order_date
) VALUES
  (
    1, 'Kwame Mensah', 'kwame@example.com', '0557605261', 'Jollof', 3, 'Dzorwulu', 'Delivery',
    'Dzorwulu / Abelemkpe / Airport Residential', 15.00, 'Dzorwulu Junction, Accra',
    'Jollof x 3 = GH₵ 240.00', 240.00,
    'Paystack', 'Paid', 'PSK_MF_902814', 'Completed', 'seen', '2026-10-02 10:23:51+00'
  ),
  (
    2, 'Ama Osei', 'ama@example.com', '0244192837', 'Multiple Foods', 2, 'Adabraka', 'Delivery',
    'Adabraka / Asylum Down / Ridge', 15.00, 'Adabraka Official Town, Accra',
    E'Jollof x 1 = GH₵ 80.00\nBanku x 1 = GH₵ 45.00', 125.00,
    'Paystack', 'Paid', 'PSK_MF_902889', 'Preparing', 'new', '2026-10-02 10:25:00+00'
  );
SELECT setval(pg_get_serial_sequence('public.orders', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.orders));

-- ---------------------------------------------------------------------
--  10. Ratings (verified guest reviews)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.ratings CASCADE;
CREATE TABLE public.ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  service_type VARCHAR(100) NOT NULL,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review TEXT,
  outlet VARCHAR(100) NOT NULL CHECK (outlet IN ('Adabraka', 'Dzorwulu')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_ratings_outlet ON public.ratings (outlet, rating, created_at DESC);

INSERT INTO public.ratings (id, customer_name, phone, service_type, rating, review, outlet, created_at) VALUES
  (1, 'Abena Darko', '0244112233', 'Food Quality', 5, 'Best smoky jollof in Accra! Flavour is consistent every time.', 'Adabraka', '2026-06-20 18:00:00+00'),
  (2, 'Kweku Appiah', '0200889900', 'Customer Service', 5, 'Quick pickup at Dzorwulu branch. Warm food and polite staff.', 'Dzorwulu', '2026-06-21 12:30:00+00');
SELECT setval(pg_get_serial_sequence('public.ratings', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.ratings));

-- ---------------------------------------------------------------------
--  11. Slider Images (hero carousel photography)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.slider_images CASCADE;
CREATE TABLE public.slider_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.slider_images (id, image_name, created_at) VALUES
  (1, 'hero.png', '2026-06-19 17:15:00+00'),
  (2, 'bankuokro.jpeg', '2026-06-19 17:15:00+00'),
  (3, 'Jollof.png', '2026-06-19 17:15:00+00'),
  (4, 'riceball.jpg', '2026-06-19 17:15:00+00');
SELECT setval(pg_get_serial_sequence('public.slider_images', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.slider_images));

-- ---------------------------------------------------------------------
--  12. Training Applications (culinary & hospitality admissions)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.training_applications CASCADE;
CREATE TABLE public.training_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_ref VARCHAR(50) NOT NULL UNIQUE,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  training_school VARCHAR(255) NOT NULL,
  program VARCHAR(255) NOT NULL,
  message TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Contacted', 'Interview Scheduled', 'Admitted', 'Archived')),
  admin_notes TEXT,
  email_sent BOOLEAN NOT NULL DEFAULT TRUE,
  confirmation_email_html TEXT,
  notification_status VARCHAR(20) NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_training_applications_status ON public.training_applications (status, created_at DESC);

INSERT INTO public.training_applications (
  id, application_ref, full_name, phone, email, training_school, program, message, status, admin_notes, email_sent, notification_status, created_at
) VALUES
  (
    1, 'MFA-2026-9041', 'Akosua Mensah', '0244192837', 'akosua@example.com',
    'Culinary Arts', 'Professional Cookery Certificate (3 Months)',
    'Passionate about authentic Ghanaian dishes and modern restaurant kitchen management.',
    'Interview Scheduled', 'Invited for kitchen practical assessment on Monday.',
    TRUE, 'seen', '2026-10-02 11:00:00+00'
  );
SELECT setval(pg_get_serial_sequence('public.training_applications', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.training_applications));

-- ---------------------------------------------------------------------
--  13. Advertisement Banners (promotional campaign cards)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.advertisement_banners CASCADE;
CREATE TABLE public.advertisement_banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  banner_image VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  button_text VARCHAR(255) NOT NULL,
  button_link VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.advertisement_banners (id, banner_image, title, description, button_text, button_link, status, created_at) VALUES
  (1, 'Jollof.png', 'Fresh Jollof Special', 'Enjoy our signature smoky party jollof served with grilled chicken. Order today!', 'Order Now', '/menu', 'Active', '2026-06-19 18:00:00+00'),
  (2, 'riceball.jpg', 'Riceball Deal', 'Quick, tasty and affordable riceballs prepared fresh every day.', 'View Menu', '/menu', 'Active', '2026-06-19 18:05:00+00');
SELECT setval(pg_get_serial_sequence('public.advertisement_banners', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.advertisement_banners));

-- ---------------------------------------------------------------------
--  14. Advertisement Videos (kitchen video showcase)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.advertisement_videos CASCADE;
CREATE TABLE public.advertisement_videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_name VARCHAR(255) NOT NULL,
  poster_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.advertisement_videos (id, video_name, poster_url, created_at) VALUES
  (1, 'video.mp4', 'hero.png', '2026-06-19 18:10:00+00');
SELECT setval(pg_get_serial_sequence('public.advertisement_videos', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.advertisement_videos));

-- Storage-backed image metadata for runtime WebP variants.
CREATE TABLE public.image_asset_metadata (
  object_key VARCHAR(191) PRIMARY KEY,
  public_url TEXT NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  color VARCHAR(16) NOT NULL,
  variants_json TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- ---------------------------------------------------------------------
--  15. Visitor Counter (tracked in Admin Analytics)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.visitor_counter CASCADE;
CREATE TABLE public.visitor_counter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  total_visitors BIGINT NOT NULL DEFAULT 0
);

INSERT INTO public.visitor_counter (id, total_visitors) VALUES (1, 1250);
SELECT setval(pg_get_serial_sequence('public.visitor_counter', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.visitor_counter));

-- Atomic visitor counter increment function for Supabase RPC
CREATE OR REPLACE FUNCTION public.increment_visitor_counter()
RETURNS BIGINT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.visitor_counter
  SET total_visitors = total_visitors + 1
  WHERE id = 1
  RETURNING total_visitors;
$$;

-- Secure customer order tracking RPC (requires matching ID and last 4 phone digits, returns non-sensitive payload)
CREATE OR REPLACE FUNCTION public.track_customer_order(p_order_id BIGINT, p_phone_last4 TEXT)
RETURNS TABLE (
  id BIGINT,
  customer_name VARCHAR(255),
  outlet VARCHAR(100),
  order_type VARCHAR(100),
  food_item VARCHAR(255),
  quantity INTEGER,
  order_details TEXT,
  delivery_zone VARCHAR(120),
  delivery_fee NUMERIC(10, 2),
  total NUMERIC(10, 2),
  payment_method VARCHAR(50),
  payment_status VARCHAR(50),
  status VARCHAR(50),
  order_date TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT
    o.id,
    o.customer_name,
    o.outlet,
    o.order_type,
    o.food_item,
    o.quantity,
    o.order_details,
    o.delivery_zone,
    o.delivery_fee,
    o.total,
    o.payment_method,
    o.payment_status,
    o.status,
    o.order_date
  FROM public.orders o
  WHERE o.id = p_order_id
    AND RIGHT(regexp_replace(o.phone, '\D', '', 'g'), 4) = RIGHT(regexp_replace(p_phone_last4, '\D', '', 'g'), 4);
END;
$$;

-- ---------------------------------------------------------------------
--  16. Website Settings (branch phones, social links, hours & Paystack)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.website_settings CASCADE;
CREATE TABLE public.website_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  adabraka_phone VARCHAR(20) NOT NULL,
  dzorwulu_phone VARCHAR(20) NOT NULL,
  facebook_link TEXT NOT NULL,
  tiktok_link TEXT NOT NULL,
  opening_hours VARCHAR(255) NOT NULL,
  paystack_public_key VARCHAR(255) NOT NULL DEFAULT 'pk_test_mayfordfoodsgh_public_key'
);

INSERT INTO public.website_settings (
  id, email, adabraka_phone, dzorwulu_phone, facebook_link, tiktok_link, opening_hours, paystack_public_key
) VALUES (
  1,
  'mayfordfoods@gmail.com',
  '0244143271',
  '0533634378',
  'https://www.facebook.com/share/1PDFLKArpt/',
  'https://www.tiktok.com/@maryafuahboakye?_r=1&_t=ZS-97IIPfQ9uRo',
  'Monday - Sunday 9:00 AM - 9:30 PM',
  'pk_test_mayfordfoodsgh_public_key'
);
SELECT setval(pg_get_serial_sequence('public.website_settings', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.website_settings));

-- ---------------------------------------------------------------------
--  17. Payment Audit Logs (tamper-proof financial transaction ledger)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.payment_audit_logs CASCADE;
CREATE TABLE public.payment_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  payment_reference VARCHAR(150) NOT NULL,
  event_type VARCHAR(50) NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'GHS',
  channel VARCHAR(50),
  gateway VARCHAR(50) NOT NULL DEFAULT 'Paystack',
  gateway_status VARCHAR(50),
  raw_payload JSONB,
  ip_address VARCHAR(45),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_payment_audit_logs_ref ON public.payment_audit_logs (payment_reference);
CREATE INDEX idx_payment_audit_logs_order ON public.payment_audit_logs (order_id);
CREATE INDEX idx_payment_audit_logs_created ON public.payment_audit_logs (created_at DESC);

-- =====================================================================
--  ROW LEVEL SECURITY (RLS) POLICIES FOR SUPABASE
--  Hardened & Audited: Closes "TO PUBLIC" default bypass & secures payments
-- =====================================================================
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catering_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.slider_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.advertisement_banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.advertisement_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_counter ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.image_asset_metadata ENABLE ROW LEVEL SECURITY;

-- 1. PUBLIC READ POLICIES (Storefront Catalog & Media via Anon Key)
CREATE POLICY "Public read banners" ON public.banners FOR SELECT USING (true);
CREATE POLICY "Public read community_media" ON public.community_media FOR SELECT USING (true);
CREATE POLICY "Public read menu_categories" ON public.menu_categories FOR SELECT USING (true);
CREATE POLICY "Public read menu_items" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Public read ratings" ON public.ratings FOR SELECT USING (true);
CREATE POLICY "Public read slider_images" ON public.slider_images FOR SELECT USING (true);
CREATE POLICY "Public read advertisement_banners" ON public.advertisement_banners FOR SELECT USING (true);
CREATE POLICY "Public read advertisement_videos" ON public.advertisement_videos FOR SELECT USING (true);
CREATE POLICY "Public read website_settings" ON public.website_settings FOR SELECT USING (true);
CREATE POLICY "Public read visitor_counter" ON public.visitor_counter FOR SELECT USING (true);

-- 2. PUBLIC INSERT POLICIES (Storefront Guest Submissions with Strict Validation)
-- NOTE: Orders must ONLY be placed through the authoritative backend API (/api/orders)
-- where prices and Paystack transactions are cryptographically verified.
-- Direct anon insertion into orders is disallowed to prevent payment tampering.

CREATE POLICY "Public insert catering_bookings" ON public.catering_bookings FOR INSERT TO anon
  WITH CHECK (
    guest_count > 0
    AND customer_name IS NOT NULL
    AND length(trim(customer_name)) >= 2
    AND phone IS NOT NULL
    AND length(trim(phone)) >= 7
    AND outlet IN ('Adabraka', 'Dzorwulu')
  );

CREATE POLICY "Public insert training_applications" ON public.training_applications FOR INSERT TO anon
  WITH CHECK (
    full_name IS NOT NULL
    AND length(trim(full_name)) >= 2
    AND phone IS NOT NULL
    AND length(trim(phone)) >= 7
    AND email IS NOT NULL
    AND length(trim(email)) >= 5
    AND program IS NOT NULL
  );

CREATE POLICY "Public insert contact_messages" ON public.contact_messages FOR INSERT TO anon
  WITH CHECK (
    full_name IS NOT NULL
    AND length(trim(full_name)) >= 2
    AND message IS NOT NULL
    AND length(trim(message)) >= 2
  );

CREATE POLICY "Public insert ratings" ON public.ratings FOR INSERT TO anon
  WITH CHECK (
    rating BETWEEN 1 AND 5
    AND customer_name IS NOT NULL
    AND length(trim(customer_name)) >= 2
    AND outlet IN ('Adabraka', 'Dzorwulu')
  );

-- 3. SERVICE ROLE POLICIES (Restricted to Backend API via Service Role Key)
-- Explicitly scoped `TO service_role` so the public Anon key NEVER inherits admin privileges.
CREATE POLICY "Service role full access admins" ON public.admins FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access admin_sessions" ON public.admin_sessions FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access banners" ON public.banners FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access catering_bookings" ON public.catering_bookings FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access community_media" ON public.community_media FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access contact_messages" ON public.contact_messages FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access menu_categories" ON public.menu_categories FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access menu_items" ON public.menu_items FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access orders" ON public.orders FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access ratings" ON public.ratings FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access slider_images" ON public.slider_images FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access training_applications" ON public.training_applications FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access advertisement_banners" ON public.advertisement_banners FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access advertisement_videos" ON public.advertisement_videos FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access visitor_counter" ON public.visitor_counter FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access website_settings" ON public.website_settings FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access payment_audit_logs" ON public.payment_audit_logs FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 4. HARDEN PERMISSIONS (Defense-in-depth: Revoke mutation and privacy leaks from public roles)
REVOKE ALL ON public.admins, public.admin_sessions, public.payment_audit_logs FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.orders FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.website_settings FROM anon, authenticated;
REVOKE SELECT ON public.orders, public.catering_bookings, public.training_applications, public.contact_messages FROM anon;

-- =====================================================================
--  SUPABASE REALTIME PUBLICATION & REPLICA IDENTITY
--  Public catalog tables only (prevents customer PII & order data leaks)
-- =====================================================================
ALTER TABLE public.visitor_counter REPLICA IDENTITY FULL;
ALTER TABLE public.menu_items REPLICA IDENTITY FULL;
ALTER TABLE public.menu_categories REPLICA IDENTITY FULL;
ALTER TABLE public.banners REPLICA IDENTITY FULL;
ALTER TABLE public.advertisement_banners REPLICA IDENTITY FULL;
ALTER TABLE public.ratings REPLICA IDENTITY FULL;
ALTER TABLE public.website_settings REPLICA IDENTITY FULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.visitor_counter;
ALTER PUBLICATION supabase_realtime ADD TABLE public.menu_items;
ALTER PUBLICATION supabase_realtime ADD TABLE public.menu_categories;
ALTER PUBLICATION supabase_realtime ADD TABLE public.banners;
ALTER PUBLICATION supabase_realtime ADD TABLE public.advertisement_banners;
ALTER PUBLICATION supabase_realtime ADD TABLE public.ratings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.website_settings;

COMMIT;
